apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: ${TEST_NAME}
  namespace: ${NAMESPACE}
spec:
  parallelism: ${PARALLELISM}
  cleanup: post
  script:
    configMap:
      name: k6-load-test-script
      file: load-test.js
  runner:
    env:
      - name: TARGET_URL
        value: "${TARGET_URL}"
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: "1"
        memory: 512Mi
