apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k6-test-runner
  namespace: compute-resources-area-calidad-dev
rules:
  - apiGroups: ["k6.io"]
    resources: ["testruns", "testjobs"]
    verbs: ["create", "get", "list", "watch", "delete", "patch", "update"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "get", "list", "watch", "delete", "patch", "update"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list", "watch"]
